# Generated by Django 5.2.6 on 2025-09-28 13:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=255)),
                ('original_file_size', models.BigIntegerField()),
                ('upload_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('file_path', models.CharField(max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompressionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compressed_filename', models.CharField(max_length=255)),
                ('compressed_file_size', models.BigIntegerField()),
                ('compression_ratio', models.FloatField()),
                ('compression_time', models.FloatField()),
                ('download_link', models.CharField(max_length=500)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='compression.file')),
            ],
        ),
    ]
