# Generated by Django 5.2.6 on 2025-10-22 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compression', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compressionresult',
            name='downloaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='compressionresult',
            name='downloaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
